/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.mait.flink.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SuperBizEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5751283084285466896L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SuperBizEvent\",\"namespace\":\"io.mait.flink.avro\",\"fields\":[{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logical-type\":\"uuid\"},{\"name\":\"eventEventId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logical-type\":\"uuid\"},{\"name\":\"eventTimestamp\",\"type\":\"long\",\"doc\":\"eventTimestamp\"},{\"name\":\"eventPublishTimestamp\",\"type\":\"long\",\"doc\":\"eventTimestamp\"}],\"doc:\":\"superBizEvent\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SuperBizEvent> ENCODER =
      new BinaryMessageEncoder<SuperBizEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SuperBizEvent> DECODER =
      new BinaryMessageDecoder<SuperBizEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SuperBizEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SuperBizEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SuperBizEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SuperBizEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SuperBizEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SuperBizEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SuperBizEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SuperBizEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String eventId;
   private java.lang.String eventEventId;
  /** eventTimestamp */
   private long eventTimestamp;
  /** eventTimestamp */
   private long eventPublishTimestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SuperBizEvent() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param eventEventId The new value for eventEventId
   * @param eventTimestamp eventTimestamp
   * @param eventPublishTimestamp eventTimestamp
   */
  public SuperBizEvent(java.lang.String eventId, java.lang.String eventEventId, java.lang.Long eventTimestamp, java.lang.Long eventPublishTimestamp) {
    this.eventId = eventId;
    this.eventEventId = eventEventId;
    this.eventTimestamp = eventTimestamp;
    this.eventPublishTimestamp = eventPublishTimestamp;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return eventEventId;
    case 2: return eventTimestamp;
    case 3: return eventPublishTimestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = value$ != null ? value$.toString() : null; break;
    case 1: eventEventId = value$ != null ? value$.toString() : null; break;
    case 2: eventTimestamp = (java.lang.Long)value$; break;
    case 3: eventPublishTimestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.String getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.String value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'eventEventId' field.
   * @return The value of the 'eventEventId' field.
   */
  public java.lang.String getEventEventId() {
    return eventEventId;
  }


  /**
   * Sets the value of the 'eventEventId' field.
   * @param value the value to set.
   */
  public void setEventEventId(java.lang.String value) {
    this.eventEventId = value;
  }

  /**
   * Gets the value of the 'eventTimestamp' field.
   * @return eventTimestamp
   */
  public long getEventTimestamp() {
    return eventTimestamp;
  }


  /**
   * Sets the value of the 'eventTimestamp' field.
   * eventTimestamp
   * @param value the value to set.
   */
  public void setEventTimestamp(long value) {
    this.eventTimestamp = value;
  }

  /**
   * Gets the value of the 'eventPublishTimestamp' field.
   * @return eventTimestamp
   */
  public long getEventPublishTimestamp() {
    return eventPublishTimestamp;
  }


  /**
   * Sets the value of the 'eventPublishTimestamp' field.
   * eventTimestamp
   * @param value the value to set.
   */
  public void setEventPublishTimestamp(long value) {
    this.eventPublishTimestamp = value;
  }

  /**
   * Creates a new SuperBizEvent RecordBuilder.
   * @return A new SuperBizEvent RecordBuilder
   */
  public static io.mait.flink.avro.SuperBizEvent.Builder newBuilder() {
    return new io.mait.flink.avro.SuperBizEvent.Builder();
  }

  /**
   * Creates a new SuperBizEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SuperBizEvent RecordBuilder
   */
  public static io.mait.flink.avro.SuperBizEvent.Builder newBuilder(io.mait.flink.avro.SuperBizEvent.Builder other) {
    if (other == null) {
      return new io.mait.flink.avro.SuperBizEvent.Builder();
    } else {
      return new io.mait.flink.avro.SuperBizEvent.Builder(other);
    }
  }

  /**
   * Creates a new SuperBizEvent RecordBuilder by copying an existing SuperBizEvent instance.
   * @param other The existing instance to copy.
   * @return A new SuperBizEvent RecordBuilder
   */
  public static io.mait.flink.avro.SuperBizEvent.Builder newBuilder(io.mait.flink.avro.SuperBizEvent other) {
    if (other == null) {
      return new io.mait.flink.avro.SuperBizEvent.Builder();
    } else {
      return new io.mait.flink.avro.SuperBizEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for SuperBizEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SuperBizEvent>
    implements org.apache.avro.data.RecordBuilder<SuperBizEvent> {

    private java.lang.String eventId;
    private java.lang.String eventEventId;
    /** eventTimestamp */
    private long eventTimestamp;
    /** eventTimestamp */
    private long eventPublishTimestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.mait.flink.avro.SuperBizEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventEventId)) {
        this.eventEventId = data().deepCopy(fields()[1].schema(), other.eventEventId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[2].schema(), other.eventTimestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.eventPublishTimestamp)) {
        this.eventPublishTimestamp = data().deepCopy(fields()[3].schema(), other.eventPublishTimestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing SuperBizEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(io.mait.flink.avro.SuperBizEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventEventId)) {
        this.eventEventId = data().deepCopy(fields()[1].schema(), other.eventEventId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[2].schema(), other.eventTimestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.eventPublishTimestamp)) {
        this.eventPublishTimestamp = data().deepCopy(fields()[3].schema(), other.eventPublishTimestamp);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.String getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public io.mait.flink.avro.SuperBizEvent.Builder setEventId(java.lang.String value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public io.mait.flink.avro.SuperBizEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventEventId' field.
      * @return The value.
      */
    public java.lang.String getEventEventId() {
      return eventEventId;
    }


    /**
      * Sets the value of the 'eventEventId' field.
      * @param value The value of 'eventEventId'.
      * @return This builder.
      */
    public io.mait.flink.avro.SuperBizEvent.Builder setEventEventId(java.lang.String value) {
      validate(fields()[1], value);
      this.eventEventId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventEventId' field has been set.
      * @return True if the 'eventEventId' field has been set, false otherwise.
      */
    public boolean hasEventEventId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventEventId' field.
      * @return This builder.
      */
    public io.mait.flink.avro.SuperBizEvent.Builder clearEventEventId() {
      eventEventId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTimestamp' field.
      * eventTimestamp
      * @return The value.
      */
    public long getEventTimestamp() {
      return eventTimestamp;
    }


    /**
      * Sets the value of the 'eventTimestamp' field.
      * eventTimestamp
      * @param value The value of 'eventTimestamp'.
      * @return This builder.
      */
    public io.mait.flink.avro.SuperBizEvent.Builder setEventTimestamp(long value) {
      validate(fields()[2], value);
      this.eventTimestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTimestamp' field has been set.
      * eventTimestamp
      * @return True if the 'eventTimestamp' field has been set, false otherwise.
      */
    public boolean hasEventTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'eventTimestamp' field.
      * eventTimestamp
      * @return This builder.
      */
    public io.mait.flink.avro.SuperBizEvent.Builder clearEventTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventPublishTimestamp' field.
      * eventTimestamp
      * @return The value.
      */
    public long getEventPublishTimestamp() {
      return eventPublishTimestamp;
    }


    /**
      * Sets the value of the 'eventPublishTimestamp' field.
      * eventTimestamp
      * @param value The value of 'eventPublishTimestamp'.
      * @return This builder.
      */
    public io.mait.flink.avro.SuperBizEvent.Builder setEventPublishTimestamp(long value) {
      validate(fields()[3], value);
      this.eventPublishTimestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'eventPublishTimestamp' field has been set.
      * eventTimestamp
      * @return True if the 'eventPublishTimestamp' field has been set, false otherwise.
      */
    public boolean hasEventPublishTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'eventPublishTimestamp' field.
      * eventTimestamp
      * @return This builder.
      */
    public io.mait.flink.avro.SuperBizEvent.Builder clearEventPublishTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SuperBizEvent build() {
      try {
        SuperBizEvent record = new SuperBizEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.String) defaultValue(fields()[0]);
        record.eventEventId = fieldSetFlags()[1] ? this.eventEventId : (java.lang.String) defaultValue(fields()[1]);
        record.eventTimestamp = fieldSetFlags()[2] ? this.eventTimestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.eventPublishTimestamp = fieldSetFlags()[3] ? this.eventPublishTimestamp : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SuperBizEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<SuperBizEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SuperBizEvent>
    READER$ = (org.apache.avro.io.DatumReader<SuperBizEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeString(this.eventEventId);

    out.writeLong(this.eventTimestamp);

    out.writeLong(this.eventPublishTimestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString();

      this.eventEventId = in.readString();

      this.eventTimestamp = in.readLong();

      this.eventPublishTimestamp = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString();
          break;

        case 1:
          this.eventEventId = in.readString();
          break;

        case 2:
          this.eventTimestamp = in.readLong();
          break;

        case 3:
          this.eventPublishTimestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










